todo/models/topic.py
from models import Model
import time


class Topic(Model):
    def __init__(self, form):
        self.title = form.get('title', '')
        self.id = None
        self.views = 0
        self.content = form.get('content', '')
        self.ct = int(time.time())
        self.ut = self.ct
        self.user_id = form.get('user_id', '')
        self.board_id = int(form.get('board_id', -1))

    @classmethod
    def get(cls, id):
        m = cls.find_by(id = id)
        m.views += 1
        m.save()
        return m


    def replies(self):
        from .reply import Reply
        ms = Reply.find_all(topic_id = self.id)
        return ms


    def reply_delete(self):
        ms = self.replies()
        for m in ms:
            m.delete(m.id)

todo/routes/reply.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
)


from routes import *

from models.reply import Reply


main = Blueprint('reply', __name__)

@main.route('/add', methods=['POST', 'GET'])
def add():
    form = request.form
    u = current_user()
    m = Reply.new(form, user_id = u.id)
    return redirect(url_for('topic.detail', id = m.topic_id))

todo/routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    abort,
)

from models.topic import Topic
from models.user import User
from models.board import Board

from routes import *


main = Blueprint('topic', __name__)

import uuid
csrf_tokens = []


@main.route('/')
def index():
    ms = Topic.all()
    token = str(uuid.uuid4())
    csrf_tokens.append(token)
    return render_template('/topic/index.html', ms=ms, token=token)


@main.route('/new', methods=['GET'])
def new():
    bs = Board.all()
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    else:
        return render_template('/topic/new.html', bs=bs)

@main.route('/add', methods=['POST'])
def add():
    form = request.form
    u = current_user()
    Topic.new(form, user_id = u.id)
    return redirect(url_for('.index'))

@main.route('/delete', methods=['GET'])
def delete():
    u = current_user()
    user_id = u.id
    id = int(request.args.get('topic_id', -1))
    t = Topic.find(id)
    author_id = t.user_id
    if user_id == author_id:
        token = request.args.get('token', '')
        if token in csrf_tokens:
            Topic.delete(id)
            t.reply_delete()
            csrf_tokens.remove(token)
            return redirect(url_for('.index'))
        else:
            abort(403)
    else:
        return redirect(url_for('index.index'))


@main.route('/detail/<int:id>')
def detail(id):
    m = Topic.get(id)
    user_id = m.user_id
    u = User.get(user_id)
    b = Board.find(m.board_id)
    return render_template('/topic/detail.html', topic=m, user=u, board_title=b.title)

todo/templates/topic/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
<div id="main">
    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
        <span class="topic_full_title">
			{{ topic.title }}
      	</span>
                <div class="changes">
            <span>
                发布于 2 天前
            </span>
                    <span>
                作者
                <a href="/profile">{{ user.username }}</a>
        	</span>
                    <span>
          	    {{ topic.views }} 次浏览
        	</span>
                    <span>
                来自 {{ board_title }}
            </span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">
                        {{ topic.content }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class='panel'>
        <div class='header'>
            <span class='col_fade'>
                <!-- 过滤器 -->
                {{ topic.replies() | count }} 回复
            </span>
        </div>
        {% for r in topic.replies() %}
        <div class='cell reply_area reply_item'>
            <div class='author_content'>
                <a href="/user/leiwei1991" class="user_avatar">
                    <img src="https://raw.githubusercontent.com/StephenYoung007/flask_Demo/master/%E5%A4%B4%E5%83%8F.jpg"
                         title="{{ r.user().username }}"/>
                </a>
                <div class='user_info'>
                    <a class='dark reply_author'>
                        {{ r.user().username }}
                    </a>
                    <a class="reply_time">
                        {{ loop.index }}楼 • 2 天前
                    </a>
                </div>
                <div class='user_action'>
                    <span>
                        <i class="fa up_btn
                          fa-thumbs-o-up
                          invisible" title="喜欢"></i>
                        <span class="up-count">
                        </span>
                    </span>
                </div>
            </div>
            <div class='reply_content from-leiwei1991'>
                <div class="markdown-text">
                    {{ r.content }}
                </div>
            </div>
        </div>
        {% endfor %}
        <div>
            <form action="{{ url_for('reply.add') }}" method="post">
                <input type="hidden" name="topic_id" value="{{ topic.id }}">
                <textarea name="content"></textarea>
                <button>添加回复</button>
            </form>
        </div>
    </div>
</body>
</html>

todo/templates/topic/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id="main">
        <div id="sidebar">
            <div class="panel">
                <div class="inner">
                    <a href="/topic/new" class="create_topic_btn">
                        <span class="span-success">发布话题</span>
                    </a>
                </div>
            </div>
        </div>
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <div class="topic_list">
                        {% for t in ms %}
                        <div class="cell">
                            <div class="topic_title_wrapper">
                                <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                    {{ t.title }}
                                </a>
{#                                <span>{{ t.replies() | count }} / {{ t.views }}</span>#}
                                <a href="{{ url_for('topic.delete', topic_id=t.id, token=token) }}">delete</a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>

todo/templates/topic/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
<form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
    <fieldset>
        <textarea autofocus class='span9' id='title'
                  name='title' rows='1'
                  placeholder="标题字数 10 字以上"></textarea>
        <span class="tab-selector">选择板块</span>
        <select name="board_id" id="board required">
            <option value="">请选择</option>
            {% for b in bs %}
            <option value="{{ b.id }}">{{ b.title }}</option>
            {% endfor %}
        </select>
        <div class='markdown_editor in_editor'>
          <div class='markdown_in_editor'>
            <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
            <div class='editor_buttons'>
              <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
            </div>
          </div>
        </div>
    </fieldset>
</form>
                </div>
            </div>
        </div>
    </div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>

todo/templates/topic/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                        <fieldset>
                            <textarea autofocus class='span9' id='title' name='title' rows='1' placeholder="标题字数 10 字以上"></textarea>
                            <div class='markdown_editor in_editor'>
                              <div class='markdown_in_editor'>
                                <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                <div class='editor_buttons'>
                                  <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
                                </div>
                              </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
<script>

  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>